module.exports = {
    SAVE_WIN_WIDTH:"SAVE_WIN_WIDTH",
    SET_All_COLLECTOR:"SET_All_COLLECTOR",
    SET_COLLECTORID:"SET_COLLECTORID",  
    SET_CHANNEL_NOTES:"SET_CHANNEL_NOTES",
    SET_CHANNEL_ID:"SET_CHANNEL_ID",
    SET_TIME_QUANTUM:"SET_TIME_QUANTUM", 
}